# Queue backed by Ring Buffer

In [1]:
import numpy as np
class Queue():
    '''
    FIFO queue.
    This queue is backed by a ring buffer in an array.
    To detect full without extra variables,
    we always leave the last ring slot empty.
    Thus, the maximum number of elements is size-1.
    '''
    def __init__(self,size):
        self.ary = np.zeros(size,np.int64)
        # The array is empty when these two are equal
        self.front = 0  # array index of next element to pop
        self.rear = 0   # array index of next empty spot
    def __repr__(self):
        return str(self.ary)+f" front={self.front} rear={self.rear}"
    def add(self,element):
        '''Insert element at rear and increment rear.'''
        if self.is_full():
            raise Exception('Cannot add to full queue')
        self.ary[self.rear]=element  # add to rear
        self.rear = self.rear + 1    # increment rear
        if self.rear == len(self.ary): # oops, wrap around
            self.rear = 0
    def is_empty(self):
        return self.front-self.rear==0
    def is_full(self):
        f,r,a = self.front,self.rear,self.ary
        return f-r==1 or f==0 and r==len(a)-1
    def pop(self):
        '''Pop front element and increment front.'''
        if self.is_empty():
            raise Exception('Cannot pop from empty queue')
        element = self.ary[self.front]  # take from front
        self.ary[self.front]=0  # not required, but improves the display
        self.front = self.front + 1     # increment front
        if self.front == len(self.ary): # oops, wrap around
            self.front = 0
        return element

In [2]:
from random import Random
def client(q):
    '''
    This client program will test a queue.
    The client starts with a pop, and empty queue is expected.
    The client adds more than it pops, and full queue is expected.
    '''
    LOOPS = RING_SIZE*2
    generator = Random()
    for i in range(LOOPS):
        try:
            if q.is_empty():
                print('empty, no pop')
            else:
                e = q.pop()
                print('popped a',e)
            if q.is_full():
                print('full, cannot add anything')
            else:
                q.add(generator.randint(10,100))
                if q.is_full():
                    print('could only add one int')
                else:            
                    q.add(generator.randint(10,100))
                    print('added two ints')
        except Exception as ex:
            print(ex)
        print(q)

In [3]:
# Demonstration: adds more than it pops
RING_SIZE = 10
q = Queue(RING_SIZE)
client(q)

empty, no pop
added two ints
[20 94  0  0  0  0  0  0  0  0] front=0 rear=2
popped a 20
added two ints
[ 0 94 42 39  0  0  0  0  0  0] front=1 rear=4
popped a 94
added two ints
[ 0  0 42 39 19 28  0  0  0  0] front=2 rear=6
popped a 42
added two ints
[ 0  0  0 39 19 28 40 51  0  0] front=3 rear=8
popped a 39
added two ints
[ 0  0  0  0 19 28 40 51 63 16] front=4 rear=0
popped a 19
added two ints
[26 57  0  0  0 28 40 51 63 16] front=5 rear=2
popped a 28
added two ints
[26 57 76 69  0  0 40 51 63 16] front=6 rear=4
popped a 40
added two ints
[26 57 76 69 52 84  0 51 63 16] front=7 rear=6
popped a 51
could only add one int
[26 57 76 69 52 84 95  0 63 16] front=8 rear=7
popped a 63
could only add one int
[26 57 76 69 52 84 95 21  0 16] front=9 rear=8
popped a 16
could only add one int
[26 57 76 69 52 84 95 21 24  0] front=0 rear=9
popped a 26
could only add one int
[ 0 57 76 69 52 84 95 21 24 16] front=1 rear=0
popped a 57
could only add one int
[75  0 76 69 52 84 95 21 24 16] front=2 rea